### ISSUE TITLE
Gray box around interface Ubuntu Unity 15.10

### ISSUE THREAD

**Issue by galgalesh** [emersion/bups#13]
As you can see in the picture, when running bups in Ubuntu unity 15.10, you get a gray box around the gui.

![bups](https://cloud.githubusercontent.com/assets/1492981/11496511/b178fd14-9812-11e5-9581-30fc689588a8.png)

Let me know if you need more info.

**Comment by emersion** [comment]
Do you have a custom theme? If so, try this: http://www.webupd8.org/2015/11/fix-large-black-borders-around-header.html

**Comment by galgalesh** [comment]
Yes, I'm using the numix theme. Thanks for your help!

2015-12-01 19:00 GMT+01:00 emersion <notifications@github.com>:
