### ISSUE TITLE
bups systemd timer won't load

### ISSUE THREAD

**Issue by jvonhoff** [emersion/bups#15]
trying to do `systemctl start bups.timer` kept failing.  Turns out, the bups.service can't start because ExecStart was being ignored.  I think it was getting ignored because of this line:

```
[/etc/systemd/system/bups.service:6] Executable path is not absolute, ignoring: python2 /usr/lib/python2.7/site-packages/bups/scheduler_worker.py /home/jeremy/.config/bups/config.json > /usr/lib/python2.7/site-packages/bups/scheduler-log.log 2>&1

bups.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```

I changed python2 to be /sbin/python2 and it seems to be working for me.

**Comment by emersion** [comment]
Thanks for reporting this issue! Related to #16
