### ISSUE TITLE
Debian package not working

### ISSUE THREAD

**Issue by galgalesh** [emersion/bups#19]
It seems something has gone wrong in the building of the latest debian package:

    bash: /usr/bin/bups: /home/travis/virtualenv/python2.7_with_system_site_packages/bin/python: bad interpreter: No such file or directory

Looking at `/usr/bin/bups` the shebang is

    #!/home/travis/virtualenv/python2.7_with_system_site_packages/bin/python

Ubuntu 16.04

**Comment by galgalesh** [comment]
Thanks for the quick fix! ETA on when the new build will be available?

**Comment by emersion** [comment]
I have been trying to setup an automatic build server with travis, but I still can't get the .deb files right. For now, I'll just to continue to build manually .deb files. The latest version is available here: https://fs.emersion.fr/public/bups/
