### ISSUE TITLE
Refactoring or complete forking?

### ISSUE THREAD

**Issue by fandjelo** [emersion/bups#29]
I like bups very much. It looks good and the idea meets my expectation of how bup GUI should be. However, I being looking through the code an saw some potential for improvements. I would like to refactor and improve the code. Depending on time, I could also add something useful. This changes would mean more or less bigger patches, so do you think it will be possible to integrate them back, in case you are happy with the quality? I'm just asking because I'm not sure if I should make something new, taking the inspiration from your idea, or just to start refactoring your code. What do you think?

**Comment by emersion** [comment]
Looking back at the code myself, I agree that it needs at least a big refactoring. I'll gladly accept PRs if you're up for it.

It depends on what you want to do. If you prefer refactoring bups piece by piece, it might be better to submit bigger PRs (though, try keeping each PR as small as possible to make code reviews easier). If you want to rebuild all from scratch, go for it.

**Comment by fandjelo** [comment]
Very cool, then I'll try to do refactoring, this is sometimes more effort, then to rewrite, but well, as I told, I like this project and would like to help a little bit.

**Comment by emersion** [comment]
Thanks! I'll review your PRs and give add you as a collaborator after one or two PRs. ;)
