### ISSUE TITLE
missing labels

### ISSUE THREAD

**Issue by atomGit** [emersion/bups#32]
kde/plasma
manjaro
bups 0.8.1-2

all of the job labels for the 'Backup Status' tray pop-up are AWOL

this was mentioned before however it appears the issue was closed, then deleted

**Comment by emersion** [comment]
>all of the job labels for the 'Backup Status' tray pop-up are AWOL

There's no popup, there's no tray. What are you talking about?

>then deleted

I've never deleted an issue.

**Comment by atomGit** [comment]
jesus-h - i got the wrong repo - sorry
