### ISSUE TITLE
Systemd support

### ISSUE THREAD

**Issue by Edenhofer** [emersion/bups#4]
Since many major linux distributions heavily depend on systemd - if one likes it or not. It is usually preinstalled. Therefore I would suggest to include systemd-timer (https://wiki.archlinux.org/index.php/Systemd/Timers) support for the periodic backups instead or in supplement to anacron.

**Comment by emersion** [comment]
Just added systemd timers support. There is an issue, you cannot control the backup frequency (it's weekly). You'll have to edit the systemd timer manually to change that.

Do you know how to execute a systemd timer each `n` days?

**Comment by Edenhofer** [comment]
To achieve this I would use the "OnActiveSec=" option in the [Timer] directive, which defines a monotonic timer relative to the moment the timer itself is activated. By the way I would use hours instead because e.g. I would like to make a snapshot every 2 hours or so. So using something like:
/etc/systemd/system/bup.timer
--------------------------------------
[Unit]
Description=Run bup every two hours
[Timer]
OnActiveSec=2hr
[Install]
WantedBy=timers.target

should do the job... If you want to read more specific information about systemd timers please refer to http://www.freedesktop.org/software/systemd/man/systemd.time.html#Parsing%20Time%20Spans and http://www.freedesktop.org/software/systemd/man/systemd.timer.html
And do not forget to trigger a daemon-reload! (https://wiki.archlinux.org/index.php/Systemd)

**Comment by emersion** [comment]
Thank you!

I have a question: if I set `OnActiveSec=7d`, the timer will be executed 7 days after it is activated. But what if the computer is shut down? Will it be executed the next time it is powered on?

**Comment by Edenhofer** [comment]
In this case the unit will immediately start.

**Comment by emersion** [comment]
Systemd timers are now fully supported.

Concerning backups each 2 hours, for the moment you can edit `/etc/systemd/system/bups.timer` manually. I've opened a new issue: #5.
