### ISSUE TITLE
Name backups and exclude files/directories

### ISSUE THREAD

**Issue by Edenhofer** [emersion/bups#6]
In bup the "-n" option can be used when saving a backup to name the output.
When indexing with bup one can use "--exclude=<PATH>" to exclude the specified directory from being indexed, moreover one can use "--exclude-rx <PATTERN>"  to not index anything that maches this pattern. This can be very useful when backup up everything under /home/<USERNAME> but one wants to exclude files and folders with a dot in front of their name.

**Comment by emersion** [comment]
Just added backup name editing in 1bd1f81ee477cf418a25351f4c9d36a6c11c10ca

**Comment by emersion** [comment]
Fixed in 9256d0308f6b7c2a46536755d74916c6bde7d229

**Comment by emersion** [comment]
It looks like this: ![](https://cloud.githubusercontent.com/assets/506932/5602590/ce7d2144-9357-11e4-9c11-714c6bcaaeaa.png)

**Comment by Edenhofer** [comment]
Thanks!
I just received the email and immediately updated the git repository :D

**Comment by emersion** [comment]
You're welcome!

I think you can update one more time your Git repo: I just fixed a bug when changing selection with the sidebar opened. ;-)

**Comment by Edenhofer** [comment]
Done...
